packages:
    - "apps/relayer"
    - "apps/mobile"
    - "apps/web"
    - "packages/backend/*"
    - "packages/database/*"
    - "packages/frontend/*"
    - "packages/shared/*"
    - "packages/frontend/design-system/*"
